# This file was automatically generated by gen_ast.py.
import dataclasses
import tokens
from typing import List, Any
class Expr:
    pass
@dataclasses.dataclass
class Binary(Expr):
    left : Expr
    operator : Token
    right : Expr
@dataclasses.dataclass
class Grouping(Expr):
    expression : Expr
@dataclasses.dataclass
class Literal(Expr):
    value : Any
@dataclasses.dataclass
class Unary(Expr):
    operator : Token
    right : Expr

